<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID коментируемой модели' => '',
    'ID родителя' => '',
    'Выберите автора' => '',
    'Выберите статус' => '',
    'Дата обновления' => '',
    'Дата создания' => '',
    'Добавить комментарий...' => '',
    'Кем обновлен' => '',
    'Кем создан' => '',
    'Комментарии' => '',
    'Комментарии ({0})' => '',
    'Комментарий' => '',
    'Комментарий был удалён' => '',
    'Комментарий не может быть пустым' => '',
    'Комментарий не найден' => '',
    'Комментарий сохранен' => '',
    'Комментарий удален' => '',
    'Комментарий: {0}' => '',
    'Модель' => '',
    'На основе {0} отзывов' => '',
    'Нажмите здесь, чтобы отменить ответ' => '',
    'Не удалось удалить комментарий. Попробуйте пожалуйста еще раз!' => '',
    'Опубликовать комментарий' => '',
    'Ответить' => '',
    'Относится к' => '',
    'Ошибка! Попробуйте пожалуйста еще раз!' => '',
    'Свойство "entityIdAttribute" должно быть установлено' => '',
    'Свойство "model" должно быть установлено' => '',
    'Статус' => '',
    'Удалить' => '',
    'Уровень вложенности' => '',
    'Чтобы оставить комментарий, нужно ' => '',
];
