<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Генерация карты сайта' => '',
    'Генерировать карту сайта' => '',
    'Карта сайта' => '',
    'Класс для создания карты сайта обновлен' => '',
    'Класс для создания карты сайта создан' => '',
    'Класс для создания карты сайта удален' => '',
    'Класс модели, например: dminmodulescatalogmodelsItem' => '',
    'Модели для генерации карты сайта' => '',
    'Параметр "priority" - от 0.1 до 1' => '',
    'Редактировать класс' => '',
    'Создать класс карты сайта' => '',
    'Текущий индексный файл карты сайта:' => '',
];
