<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'SEO тексты' => '',
    'SEO шаблон для description' => '',
    'SEO шаблон для h1' => '',
    'SEO шаблон для keywords' => '',
    'SEO шаблон для title' => '',
    'SEO шаблон для категорий' => '',
    'SEO шаблон для элементов' => '',
    'SEO шаблон не найден!' => '',
    'SEO шаблоны' => '',
    'Заголовок API объекта' => '',
    'Ключ' => '',
    'Привести к нижнему регистру' => '',
    'Редактировать SEO шаблон' => '',
    'Создать SEO шаблон' => '',
    'Шаблон обновлен' => '',
    'Шаблон создан' => '',
    'Шаблон удален' => '',
];
