<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Вы можете связаться с нами через форму обратной связи' => 'You can contact us via the feedback form',
    'Apple iPhone' => 'Apple iPhone',
    'FAQ' => 'FAQ',
    'Бренд' => 'Brand',
    'Бренды' => 'Brands',
    'Время работы' => 'Opening hours',
    'Все новости' => 'All the news',
    'Вход' => 'Login',
    'Выход' => 'Logout',
    'Галлереи' => 'Gallery',
    'Главная' => 'Main',
    'Заказ обратного звонка' => 'Request a callback',
    'Заказать звонок!' => 'Call me!',
    'Каталог' => 'Catalog',
    'Категория' => 'Category',
    'Контакты' => 'Contacts',
    'Корзина' => 'Shopping cart',
    'Макс. цена' => 'Max price',
    'Мин. цена' => 'Min price',
    'Мои заказы' => 'My orders',
    'Мы используем' => 'We use',
    'Новинки' => 'New',
    'Ой! Что-то пошло не так' => 'Oops! Error...',
    'Основной цвет' => 'Base color',
    'Подписаться на рассылку' => 'Subscribe',
    'Прайс-лист в Excel' => 'Excel price list',
    'Регистрация' => 'Registration',
    'Скачать прайс-лист' => 'Download price list',
    'Статьи' => 'Articles',
    'Страница' => 'Page',
];
